# Generated by Django 3.1 on 2020-09-01 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('carNumber', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='Petrol',
            fields=[
                ('brand', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Бензин',
                'verbose_name_plural': 'Бензин',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litre', models.PositiveSmallIntegerField()),
                ('tradeDateTime', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='App.car')),
                ('petrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='App.petrol')),
            ],
            options={
                'verbose_name': 'Refuelling',
                'verbose_name_plural': 'Refuelling',
            },
        ),
    ]
