# Generated by Django 3.1 on 2020-09-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_trade_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
    ]
