# Generated by Django 3.1 on 2020-09-11 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20200901_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oil',
            fields=[
                ('name', models.CharField(max_length=63, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('RemainingLitres', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('RemainingBottles', models.PositiveIntegerField(default=0)),
                ('bottleVolume', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('created', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Oil',
                'verbose_name_plural': 'Oils',
            },
        ),
        migrations.CreateModel(
            name='OilTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litreSold', models.DecimalField(decimal_places=1, max_digits=4)),
                ('tradePrice', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dateTime', models.DateTimeField(blank=True)),
                ('oil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='App.oil')),
            ],
            options={
                'verbose_name': 'Oil Trade',
                'verbose_name_plural': 'Oil Trades',
            },
        ),
    ]
