# Generated by Django 3.1 on 2020-09-11 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_oil_oiltrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='OilCheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottles', models.PositiveIntegerField(default=0)),
                ('dateTime', models.DateTimeField(blank=True)),
                ('oil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='App.oil')),
            ],
        ),
    ]
