# Generated by Django 3.1 on 2020-09-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_oilcheckin'),
    ]

    operations = [
        migrations.AddField(
            model_name='oil',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
