# Generated by Django 3.1 on 2020-09-16 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_oil_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oilcheckin',
            name='dateTime',
        ),
        migrations.AddField(
            model_name='oilcheckin',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
