# Generated by Django 3.1 on 2020-09-19 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20200916_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('name', models.CharField(max_length=31, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='App.carmodel'),
        ),
    ]
