# Generated by Django 3.1 on 2020-09-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20200919_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='tradeDateTime',
            field=models.DateTimeField(blank=True),
        ),
    ]
