# Generated by Django 3.1 on 2020-09-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20200927_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petrol_bonus_limit', models.PositiveSmallIntegerField(default=500)),
            ],
        ),
    ]
