# Generated by Django 3.1 on 2020-09-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='total_litres_after_bonus',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
