# Generated by Django 3.1 on 2020-09-27 17:12

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_car_total_litres_after_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='created_by',
            field=models.ForeignKey(default=App.models.get_super_user, on_delete=models.SET(App.models.get_super_user), related_name='created_cars', to='App.member'),
        ),
        migrations.AddField(
            model_name='oil',
            name='created_by',
            field=models.ForeignKey(default=App.models.get_super_user, on_delete=models.SET(App.models.get_super_user), related_name='created_oils', to='App.member'),
        ),
        migrations.AddField(
            model_name='oilcheckin',
            name='created_by',
            field=models.ForeignKey(default=App.models.get_super_user, on_delete=models.SET(App.models.get_super_user), related_name='created_oil_checkins', to='App.member'),
        ),
        migrations.AddField(
            model_name='oiltrade',
            name='created_by',
            field=models.ForeignKey(default=App.models.get_super_user, on_delete=models.SET(App.models.get_super_user), related_name='created_oil_trades', to='App.member'),
        ),
        migrations.AddField(
            model_name='trade',
            name='created_by',
            field=models.ForeignKey(default=App.models.get_super_user, on_delete=models.SET(App.models.get_super_user), related_name='created_petrol_trades', to='App.member'),
        ),
    ]
