# Generated by Django 3.1 on 2020-09-29 15:58

import App.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_auto_20200927_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity_measure', models.CharField(choices=[('litre', 'Litre'), ('piece', 'Piece'), ('metre', 'Metre'), ('kilogram', 'Kilogram')], max_length=31)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradePrice', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sold_product_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dateTime', models.DateTimeField()),
                ('created_by', models.ForeignKey(default=App.models.get_super_user, on_delete=models.SET(App.models.get_super_user), related_name='created_product_trades', to='App.member')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='App.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_product_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date', models.DateField()),
                ('created_by', models.ForeignKey(default=App.models.get_super_user, on_delete=models.SET(App.models.get_super_user), related_name='created_product_checkins', to='App.member')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='App.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='App.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(default=App.models.get_super_user, on_delete=models.SET(App.models.get_super_user), related_name='created_products', to='App.member'),
        ),
    ]
