# Generated by Django 3.1 on 2020-09-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_auto_20200929_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
