# Generated by Django 3.1 on 2020-10-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_auto_20200930_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='quantity_measure',
            field=models.CharField(choices=[('Litr', 'Litre'), ('Dona', 'Piece'), ('Metr', 'Metre'), ('Kg', 'Kilogram')], max_length=31),
        ),
    ]
