# Generated by Django 3.1 on 2020-10-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_auto_20201002_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remaining_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='bonus_limit_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='has_bonus',
            field=models.BooleanField(default=False),
        ),
    ]
