# Generated by Django 3.1 on 2020-10-02 16:40

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_auto_20201002_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=models.SET(App.models.get_product_default_category), related_name='products', to='App.productcategory'),
        ),
    ]
