# Generated by Django 3.1 on 2020-10-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_auto_20201010_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='staffs',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_categories', to='App.Member'),
        ),
    ]
