# Generated by Django 3.1 on 2020-10-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_productcategory_staffs'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='daily_car_bonus_check_limit',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
